src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discharge_Date__c</fullName>
        <label>Discharge Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Account_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Discharged</fullName>
    </customValue>
    <masterLabel>Account Status</masterLabel>
</GlobalValueSet>

src/classes/CreateFollowUpSchedules_TestClass.cls
@isTest(seeAllData=true)
public class CreateFollowUpSchedules_TestClass {

        static testMethod void testingMethod(){
        Account acc1 = new Account();
        acc1.name = 'Mirketa_Test_Patient_FollowUpcreate';
        acc1.discharge_date__c = system.now();
        acc1.Account_Status__c ='Admitted';
        insert acc1;
        
    	acc1.Account_Status__c = 'Discharged';
    	update acc1;
        
        acc1.Account_Status__c ='Admitted';
        update acc1;
        
        
    }  
    
}