src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Group_Number__c</fullName>
        <label>Group Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Phone__c</fullName>
        <label>Insurance Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Patient_SSN__c</fullName>
        <label>Patient SSN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Referred_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referring Facility</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_DOB__c</fullName>
        <label>Subscriber DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscriber_Employer__c</fullName>
        <label>Subscriber Employer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Name__c</fullName>
        <label>Subscriber Name</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DOB__c</fullName>
        <description>Date of Birth</description>
        <label>DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>male</fullName>
                </value>
                <value>
                    <fullName>female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <description>Group Number</description>
        <label>Group Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Company_Name__c</fullName>
        <description>Insurance Company Name</description>
        <label>Insurance Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Insurance_Phone__c</fullName>
        <description>Phone number for provider services.</description>
        <label>Insurance Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Member_ID_Number__c</fullName>
        <description>Member ID Number</description>
        <label>Member ID Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_SSN__c</fullName>
        <label>Patient SSN</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Primary Insurance?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referred_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referring Facility</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads (Referred By)</relationshipLabel>
        <relationshipName>anyname</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Secondary_Ins_Group_No__c</fullName>
        <label>Secondary Ins Group No</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Ins_Member_ID__c</fullName>
        <label>Secondary Ins Member ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Ins_Sub_DOB__c</fullName>
        <label>Secondary Ins Sub DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Secondary_Ins_Sub_Last_Name__c</fullName>
        <label>Secondary Ins Sub Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Ins_Sub_Phone__c</fullName>
        <label>Secondary Ins Sub Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secondary_Ins_Sub_email__c</fullName>
        <label>Secondary Ins Sub email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Ins_Subscriber_Address__c</fullName>
        <label>Secondary Ins Subscriber Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Secondary_Ins_Subscriber_Employer__c</fullName>
        <label>Secondary Ins Subscriber Employer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Ins_Subscriber_First_Name__c</fullName>
        <label>Secondary Ins Subscriber First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Insurance_Company__c</fullName>
        <label>Secondary Insurance Company</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Insurance_Phone_Number__c</fullName>
        <label>Secondary Insurance Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Secondary_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Secondary Insurance?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscriber_Address__c</fullName>
        <description>Subscriber Address</description>
        <label>Subscriber Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_City__c</fullName>
        <label>Subscriber City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_DOB__c</fullName>
        <description>Subscriber Date of Birth</description>
        <label>Subscriber DOB</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subscriber_Email__c</fullName>
        <description>Subscriber Email</description>
        <label>Subscriber Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Subscriber_Employer__c</fullName>
        <label>Subscriber Employer</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Name__c</fullName>
        <description>Subscriber Name</description>
        <label>Subscriber Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Phone__c</fullName>
        <description>Subscriber Phone</description>
        <label>Subscriber Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Subscriber_Relationship__c</fullName>
        <description>Subscriber Relationship</description>
        <label>Subscriber Relationship</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/CreateVobTriggerHelperTest.cls
@isTest
public class CreateVobTriggerHelperTest {

    @isTest
    public static void testVOBfrmLead(){
        Account ac = new Account(Name ='Referral_Test');
        insert ac;
        lead newLead = new lead(lastName ='Testlead1',Referred_By__c = ac.id,Status ='Pending',Primary_Insurance__c=true,Secondary_Insurance__c=true
                               );
        newLead.Patient_SSN__c ='1122';
        newLead.DOB__c = Date.valueOf('1997-02-02');
        newLead.Phone = '9867787898';
        newLead.Patient_SSN__c ='901';
        newLead.City = 'West Palm Beach';
        newLead.Street = '123 Datura Street';
       // newLead.State = 'FL';
        newLead.PostalCode ='133035';
        newLead.Gender__c ='Male';
        newLead.Email = 'testemail1@gmail.com';
        //newLead.LeadSource = 'Readmit';
        
        newLead.Insurance_Company_Name__c ='TestMNC';
        newLead.Insurance_Phone__c = '9998887776';
        newLead.Member_ID_Number__c ='111';
        newLead.Group_Number__c = '100';
        newLead.Subscriber_Address__c = 'ABC,CA 129,USA';
        newLead.Subscriber_City__c = 'LANE 11';
        newLead.Subscriber_DOB__c = Date.valueOf('1995-02-02');
        newLead.Subscriber_Employer__c = 'TestEmp1';
        newLead.Subscriber_Email__c = 'testmamta@gmail.com';
        newLead.Subscriber_Name__c ='Annie Grey';
        newLead.Subscriber_Phone__c = '1122334421';
        newLead.Subscriber_Relationship__c = 'self';
        
        newLead.Secondary_Insurance_Company__c = 'TestMNC2';
        newLead.Secondary_Insurance_Phone_Number__c = '5456782310';
        newLead.Secondary_Ins_Member_ID__c ='23';
        newLead.Secondary_Ins_Group_No__c ='78';
        newLead.Secondary_Ins_Subscriber_Address__c = 'MG,Test 10, IND';
        newLead.Secondary_Ins_Subscriber_Employer__c = 'SecondaryEmpTest';
        newLead.Secondary_Ins_Sub_DOB__c = Date.valueOf('1994-02-10');
        newLead.Secondary_Ins_Sub_email__c = 'testsecmamta@gmail.com';
        newLead.Secondary_Ins_Sub_Phone__c = '5456782310';
        newLead.Secondary_Ins_Sub_Last_Name__c = 'Manny';
        newLead.Secondary_Ins_Subscriber_first_name__c ='Ranni';
        
        
        
        Test.startTest();
        
        insert newLead;
        
        
        Database.LeadConvert lc = new Database.LeadConvert();
        lc.setLeadId(newLead.id);
        
        LeadStatus convertStatus =[SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        Map<id,Lead> mp= new Map<id,Lead>();
        mp.put(lcr.getOpportunityId(), newLead);
        CreateVobTriggerHelper.oppIDLeadMap = mp;
        MultipleTriggerCalls.isVobCreated =true;
        system.debug('err '+ lcr.getErrors());
        system.debug('err '+ lcr);

        system.assert(lcr.isSuccess());
        Test.stopTest();
        
    }
}