src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Alumni_Rep__c</fullName>
        <label>Alumni Rep</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Nick Newcity</fullName>
                </value>
                <value>
                    <fullName>Katie Gibson</fullName>
                </value>
                <value>
                    <fullName>Calen Cox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discharge_Date__c</fullName>
        <label>Discharge Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Patient_Follow_Up__c.object
<CustomObject>
    <fields>
        <fullName>Follow_Up_Counter__c</fullName>
        <label>Follow Up Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Date__c</fullName>
        <label>Follow Up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Status__c</fullName>
        <label>Follow Up Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Patient_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients Follow Up (Patient Name)</relationshipLabel>
        <relationshipName>Patients_Follow_Up2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rep_Name__c</fullName>
        <label>Rep Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prateek</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Patient Follow Up</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Patient Follow Up Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients Follow Up</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Schedule_Frequency__c.object
<CustomObject>
    <fields>
        <fullName>Counter_Number__c</fullName>
        <label>Counter Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Days__c</fullName>
        <label>Number of Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Schedule Frequency</label>
    <nameField>
        <label>Schedule Frequency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Frequencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Account_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Discharged</fullName>
    </customValue>
    <masterLabel>Account Status</masterLabel>
</GlobalValueSet>

src/classes/createFollowUpSchedules.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* summary of this class.
*
* Creates 8 patient follow up records after patient gets discharged.
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Anusha Prasad
* @created        2020-12-12
* 
**/

global class createFollowUpSchedules {
  
    @invocablemethod
    public static void createFollowUpRecords(List<Id> accountId){
        try{
    // Querying the Patient Name, Sales Rep and Discharge Date of the patient
    system.debug('pateint follow up creation class'+accountId);
    Account patientDetails = [Select id, name, Alumni_Rep__c, Account_Status__c, discharge_date__c from account where id in :accountId];
    
    // Querying the Schedule Frequency records 
    
    List<schedule_frequency__c> listOfSchedules = [select Counter_Number__c , Number_of_days__c from schedule_frequency__c];    
    
    // Creating list to store the Patient Follow Up records to be created
    
    List<Patient_Follow_Up__c> followUpRecordsToBeInserted = new List<Patient_Follow_Up__c>();
        
        // Iterating over Schedule frequency records to create Patient Follow Up records
        for(schedule_frequency__c scheduleFrequency:listOfSchedules){            
                Patient_Follow_Up__c followUp = new Patient_Follow_Up__c();
                
                Integer NumberOfDays = schedulefrequency.Number_of_days__c.intValue();
            
                followUp.Follow_Up_Counter__c = scheduleFrequency.Counter_Number__c;
                followUp.Follow_Up_Date__c = patientDetails.Discharge_date__C.addDays(NumberOfDays);
                followUp.Patient_Name__c = patientDetails.id;
                followUp.Rep_Name__c = patientDetails.Alumni_Rep__c;
            	followUp.Follow_Up_Status__c='Scheduled';
                followUpRecordsToBeInserted.add(followUp);
        }    
        
        insert followUpRecordsToBeInserted;

    }catch(NullPointerException e){
        System.debug('The error is in Line: '+ e.getLineNumber());
    }
    }

}