src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Status__c</fullName>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Account_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Discharge_Date__c</fullName>
        <label>Discharge Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Patient_Follow_Up__c.object
<CustomObject>
    <fields>
        <fullName>Follow_Up_Counter__c</fullName>
        <label>Follow Up Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Date__c</fullName>
        <label>Follow Up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Follow_Up_Status__c</fullName>
        <label>Follow Up Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Patient_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients Follow Up (Patient Name)</relationshipLabel>
        <relationshipName>Patients_Follow_Up2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rep_Name__c</fullName>
        <label>Rep Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Prateek</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Patient Follow Up</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Patient Follow Up Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients Follow Up</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/Account_Status.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Admitted</fullName>
    </customValue>
    <customValue>
        <fullName>Discharged</fullName>
    </customValue>
    <masterLabel>Account Status</masterLabel>
</GlobalValueSet>

src/classes/PatientFollowUpHandler_TestClass.cls
@isTest(seeAllData=true)
public class PatientFollowUpHandler_TestClass {
    static testMethod void testMethod1(){
        Account acc1 = new Account();
        acc1.Name = 'Anu2sha_1';
        acc1.Discharge_Date__c = system.now();
        acc1.Account_Status__c = 'Admitted';
        insert acc1;
        
        acc1.Account_Status__c = 'Discharged';
        update acc1;
        
        List<Patient_follow_up__c> pt1 = [select id, patient_name__c,rep_name__c, follow_up_date__c, follow_up_counter__c,Follow_Up_Status__c from patient_follow_up__c where patient_name__c = :acc1.Id order by follow_up_date__c asc];
		
        for(Patient_follow_up__c pf1 : pt1){
            
            if(pf1.follow_Up_counter__c == 1){
                pf1.follow_up_date__c = pf1.follow_up_date__c.addDays(14);
                test.startTest();
                update pf1;
                test.stopTest();
            }
        }
        
    }
    
    static testMethod void testMethod2(){
        Account acc1 = new Account();
        acc1.Name = 'Pra3sad_5';
        acc1.Discharge_Date__c = system.now();
        acc1.Account_Status__c = 'Admitted';
        insert acc1;
        
        acc1.Account_Status__c = 'Discharged';
        update acc1;
        
        List<Patient_follow_up__c> pt1 = [select id, patient_name__c,rep_name__c, follow_up_date__c, follow_up_counter__c,Follow_Up_Status__c from patient_follow_up__c where patient_name__c = :acc1.Id order by follow_up_date__c asc];
		
        for(Patient_follow_up__c pf1 : pt1){
            
            if(pf1.follow_Up_counter__c == 1){
                pf1.follow_up_date__c = pf1.follow_up_date__c.addDays(34);
                test.startTest();
                update pf1;
                test.stopTest();
            }
        }
        
    }
    
    static testMethod void testMethod3(){
        Account acc1 = new Account();
        acc1.Name = 'Prat4eek_6';
        acc1.Discharge_Date__c = system.now();
        acc1.Account_Status__c = 'Admitted';
        insert acc1;
        
        acc1.Account_Status__c = 'Discharged';
        update acc1;
        
        List<Patient_follow_up__c> pt1 = [select id, patient_name__c,rep_name__c, follow_up_date__c, follow_up_counter__c,Follow_Up_Status__c from patient_follow_up__c where patient_name__c = :acc1.Id order by follow_up_date__c asc];
		
        for(Patient_follow_up__c pf1 : pt1){
            
            if(pf1.follow_Up_counter__c == 8){
                pf1.Follow_Up_Status__c = 'Completed';
                pf1.follow_up_date__c = pf1.follow_up_date__c.addDays(2);
                Test.startTest();
                update pf1;
                Test.stopTest();
            }
        }
        
    }
    
}