src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Primary_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VOB Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secondary_Ins_Sub_Last_Name__c</fullName>
        <label>Subsciber Last Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Ins_Subscriber_First_Name__c</fullName>
        <label>Subscriber First Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Insurance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VOB Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscriber_Address2__c</fullName>
        <label>Subscriber Address 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Address__c</fullName>
        <label>Subscriber Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_City__c</fullName>
        <label>Subscriber City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_First_Name__c</fullName>
        <label>Subscriber First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Last_Name__c</fullName>
        <label>Subscriber Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_State__c</fullName>
        <label>Subscriber State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
                <value>
                    <fullName>New Jersey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscriber_Street_Address__c</fullName>
        <label>Subscriber Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Zip__c</fullName>
        <label>Subscriber Zip</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VobCreationOnOpportunityTest.cls
@isTest
public class VobCreationOnOpportunityTest {

    @isTest
    private static void testVOBCreateOnOpportunityInsertAndUpdate(){
        //first insert account
        Account ac = new Account(Name='TestAccount1');
        insert ac;
        
        //insert opportunity-cover after insert scenerio
        MultipleTriggerCalls.isVobCreated =true;
        Opportunity opp = new Opportunity(Name='TestOpportunity1',StageName='Prospect',CloseDate=Date.today(),Primary_Insurance__c=true,Secondary_Insurance__c=true);
        opp.Subscriber_First_Name__c = 'SUBFIRST1';
        opp.Subscriber_Last_Name__c ='SUBLAST1';
        opp.Secondary_Ins_Subscriber_First_Name__c ='SUBFIRST2';
        opp.Secondary_Ins_Sub_Last_Name__c = 'SUBLAST2';
        opp.Subscriber_Street_Address__c = 'STREET1';
        opp.Subscriber_Address__c = 'Address1';
        opp.Subscriber_Address2__c = 'Address2';
        opp.Subscriber_City__c = 'TESTCity';
        opp.Subscriber_State__c = 'Alabama';
        opp.Subscriber_Zip__c = '90008';
        insert opp;
         MultipleTriggerCalls.isVobCreated =true;
        
        //insert new opportunity - to cover after update scenerio
       // Opportunity oppUpdate = new Opportunity(Name='TestOpportunity2',StageName='Prospect',CloseDate=Date.today());
       // insert oppUpdate;
        opp.Primary_Insurance__c = true;
        opp.Secondary_Insurance__c = true;
        opp.Subscriber_First_Name__c = 'SUBFIRST1';
        opp.Subscriber_Last_Name__c ='SUBLAST1';
        opp.Secondary_Ins_Subscriber_First_Name__c ='SUBFIRST2';
        opp.Secondary_Ins_Sub_Last_Name__c = 'SUBLAST2';
        opp.Subscriber_Street_Address__c = 'STREET1';
        opp.Subscriber_Address__c = 'Address1';
        opp.Subscriber_Address2__c = 'Address2';
        opp.Subscriber_City__c = 'TESTCity';
        opp.Subscriber_State__c = 'Alabama';
        opp.Subscriber_Zip__c = '90008';
        Test.startTest();
        MultipleTriggerCalls.isVobCreated =true;
        update opp;
        Test.stopTest();
    }
}