src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Emergency_Contact_Name__c</fullName>
        <label>Emergency Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Phone__c</fullName>
        <label>Emergency Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Admission_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Pre-assessment</description>
        <label>Pre-Admission Assessment</label>
        <referenceTo>Pre_Admission_Assessment__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preferred_Name__c</fullName>
        <label>Preferred Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Pre_Admission_Assessment__c.object
<CustomObject>
    <fields>
        <fullName>Emergency_Contact_Name__c</fullName>
        <label>Emergency Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_Contact_Phone__c</fullName>
        <label>Emergency Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Pre-Admission Assessments</relationshipLabel>
        <relationshipName>Pre_Admission_Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Preferred_Name__c</fullName>
        <label>Preferred Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pre-Admission Assessment</label>
    <nameField>
        <label>Pre-Admission Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pre-Admission Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PreAssessmentNameSetTest.cls
@isTest
public class PreAssessmentNameSetTest {

    @isTest
    private static void testPreassessmentTrigger(){
        //insert opportunity
        Account ac = new Account(Name ='TestAccount1');
        insert ac;
        Opportunity opp = new Opportunity(Name='TestOpp1',StageName='Prospect',CloseDate=Date.today(),AccountId=ac.id,
                                         Patient_First_Name__c='P1Test',Patient_Last_Name__c='Matt',Middle_Name__c='MidName',Preferred_Name__c='PrName',
                                         Emergency_Contact_Name__c='MamtaTest',Emergency_Contact_Phone__c='9050548990');
        insert opp;
        Pre_Admission_Assessment__c preassess= new Pre_Admission_Assessment__c(Name ='Preassess1',Opportunity__c=opp.id);
        insert preassess;
      
    }
}