src/objects/Patient_Follow_Up__c.object
<CustomObject>
    <fields>
        <fullName>Follow_Up_Status__c</fullName>
        <label>Follow Up Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Unsuccessful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Patient_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Patients Follow Up (Patient Name)</relationshipLabel>
        <relationshipName>Patients_Follow_Up2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Patient Follow Up</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Patient Follow Up Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients Follow Up</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/cancelRecordsAdmitted.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* summary of this class.
*
* Deletes unsuccessful patient follow up records when the same patient admits again.
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Anusha Prasad
* @created        2020-12-12
* 
**/
global class cancelRecordsAdmitted {
    @invocableMethod
    public static void deleteCancelledRecords(List<ID> accountId){
        List<Patient_Follow_Up__c> cancelledRecords = new List<Patient_Follow_Up__c>();
        cancelledRecords = [select id, patient_name__c from Patient_Follow_Up__c where patient_name__c =:accountId and Follow_Up_Status__c='Unsuccessful'];
        delete cancelledRecords;
        
    }
    

}